### ISSUE TITLE
Faild to find library Qt5Widgets Qt5Gui Qt5Core on Mac OS

### ISSUE THREAD

**Issue by stonejiang208** [DOCGroup/MPC#105]
Under Mac OS, I tried to generate QT project script with MPC instead of qmake. I set $QTDIR=/usr/local/opt/qt. The libraries  in $QTDIR/frameworks.  But MWC can't  find them. 

How to use QT with ACE on Mac OS?  Thanks.

**Comment by iguessthislldo** [comment]
Did you set `$QT5_LIBDIR`? [MPC defaults that variable to `$QTDIR/lib`.](https://github.com/DOCGroup/MPC/blob/edd85414def6470647fae22899b2d07df5be7f3a/config/qt5_core.mpb#L10-L13)

**Comment by mouse07410** [comment]
The problem is that Qt5 (at least Macports-installed) does **not** provide these libraries. Instead, there's `/opt/local/libexec/qt5/lib/QtWidgets.framework`. 

How to tell MPC to use `-framework QtWidgets` instead of `-lQt5Widgets`?

**Comment by ocielliottc** [comment]
I don't have a Mac or use Qt5.  But, if this is still an issue, I can try to help.

As far as telling MPC to use `-framework QtWidgets` instead of `-lQt5Widgets`, you could add the following to your mpc file:

`  lit_libs -= Qt5Widgets$(QT5_LIBSUFFIX)
  specific {
    compile_flags += -framework QtWidgets
  }
`

**Comment by stonejiang208** [comment]
# 编译器和编译选项
CXX = clang++
CXXFLAGS = -std=c++11 -Wall

# Qt5 头文件路径（直接引用环境变量）
QTINC = $(QTDIR)/lib/QtWidgets.framework/Versions/5/Headers
QTLIB = $(QTDIR)/lib

# Qt5 Frameworks 路径
QTFRAMEWORKS = $(QTDIR)/lib/QtGui.framework $(QTDIR)/lib/QtWidgets.framework

QTFRAMEWORKS = QtWidgets QtGui QtCore
# 在现有的 CXXFLAGS 中添加 Qt5 头文件路径
CXXFLAGS += -I$(QTINC)

# 目标文件和源文件
TARGET = HelloWorldQt
SOURCES = main.cpp

# 生成目标文件和可执行文件
all: $(TARGET)

$(TARGET): $(SOURCES)
	#$(CXX) $(CXXFLAGS) -o $(TARGET) $(SOURCES) -F$(QTLIB) $(addprefix -framework , $(notdir $(QTFRAMEWORKS)))
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SOURCES) -F$(QTLIB) $(addprefix -framework , $(QTFRAMEWORKS)) -framework QtCore -framework DiskArbitration -framework IOKit


clean:
	rm -f $(TARGET)
