### ISSUE TITLE
Turn off GNU compiler optimizations?

### ISSUE THREAD

**Issue by NyaliaLui** [DOCGroup/MPC#126]
Hello,
Is there a way to turn off GNU compiler optimizations from the `.mpc` file?
My workaround for this is to remove the -O flags from the `GENFLAGS` macros in every Makefile but that is quite cumbersome.

Thank you for the assistance.

**Comment by ocielliottc** [comment]
I assume you are using the 'make' project type.  If you add the following to your command line, it should cause GENFLAGS to be empty:

-value_template optimize=

**Comment by NyaliaLui** [comment]
Thank you @ocielliottc that worked well.
For anyone that sees this in the future, what I did was add the following in a `.mwc` file.

__Sample.mpc__
project (Sample) {
  exename = Sample
  install = .

  // GNUmake specific flag to enable c++11
  specific(make) {
    compile_flags += -std=c++11
  }

  Source_Files {
    main.cpp
  }
}

__Sample.mwc__
workspace (Sample) {
  //Turn off compiler optimizations
  cmdline += -value_template optimize=
  Sample.mpc
}

__Run MPC__
$MPC_ROOT/mwc.pl -type make Sample.mwc
