### ISSUE TITLE
Shared library and executable with the same name result in two libraries with the same name

### ISSUE THREAD

**Issue by jwillemsen** [DOCGroup/MPC#130]
Reported by https://github.com/microsoft/vcpkg/issues/16551, at the moment the user does a Visual Studio release build there is a tao_cosnaming.lib created for the tao_cosnaming DLL but also the EXE. In debug mode there is a tao_cosnaming.lib and tao_cosnamingd.lib.

vcpkg does a copy of all lib files into the install directory, with debug we just get one of the two libraries, in release we get both.

**Comment by mitza-oci** [comment]
I think I've seen this before.  I'm not sure why a `*.lib` file is generated for an executable project.

**Comment by mitza-oci** [comment]
Based on what I saw in the vcpkg issue, this is for `-type vs2019`.

**Comment by mitza-oci** [comment]
I tried a simple example without any DOCGroup/ACE_TAO code.  The MPC-generated projects didn't create any `*.lib` files when building the executable project in Debug or Release.

```
project(*lib) {
  sharedname = mpc130
}

project(*exe) {
  exename = mpc130
  macros += BUILD_EXE
}
```

```
#ifdef BUILD_EXE
int main() {}
#else
__declspec(dllexport) void foo() {}
#endif
```

**Comment by jwillemsen** [comment]
Maybe related to https://github.com/DOCGroup/ACE_TAO/issues/1705?

**Comment by mitza-oci** [comment]
I'm not sure changing base projects would influence this, seems to be more related to the template itself.

I couldn't reproduce the problem with `vcpkg install ace[ssl,tao,wchar,xml,zlib]` so maybe no longer an issue?

**Comment by jwillemsen** [comment]
the vcpkg ace port file removes the duplicate libs, see https://github.com/microsoft/vcpkg/blob/35443ee2753f46c52ac342fa6c9c48e9f5eb9105/ports/ace/portfile.cmake#L315

**Comment by mitza-oci** [comment]
I was able to reproduce the `vcpkg` problem by commenting-out the workaround CMake code.  I suppose the next step is to reproduce with just TAO_ACE.mwc outside of vcpkg.

**Comment by mitza-oci** [comment]
OK, I can reproduce the issue and see the root cause.  When the module has exports (even if it's an EXE, since EXE and DLL are really the same thing), `link.exe` creates an export lib file.  I'll look through the exports to see how we can fix it.

**Comment by mitza-oci** [comment]
It's a TAO issue, not an MPC issue.
