### ISSUE TITLE
How to make static library with make.mpd, Is here a bug?

### ISSUE THREAD

**Issue by LukeMouse** [DOCGroup/MPC#151]
I'm working under linux recently, and I want to create a static library, so my mpc file as follow
project(XXX){
    staticname=XXX
    ...
}
but when I use mwc.pl to generate make type project script, I got the Makefile as follow:
......
AREXT         = .a
LIB           = $(LTARGETDIR)$(LIBPREFIX)BaseClassesus$(LIBSUFFIX)$(AREXT)
SOEXT         = .so **// **here**
SHTARGETDIR   = ./
SHLIB         = $(SHTARGETDIR)$(LIBPREFIX)BaseClassesus$(LIBSUFFIX)$(SOEXT)
... 
all: $(SHLIB)  // **and here**

$(SHLIB): $(OBJS) $(DEPLIBS)
	@$(TESTDIRSTART) "$(SHTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(SHTARGETDIR)"
	$(LINK.cc) $(SHFLAGS) $(OBJS) $(LDLIBS) $(OUTPUT_OPTION)

but par of the make.mpd file as follow
....
<%if(staticname)%>
AREXT         = <%lib_ext%>
LIB           = $(LTARGETDIR)$(LIBPREFIX)<%staticname%>$(LIBSUFFIX)$(AREXT)
<%endif%>
<%endif%>
<%if(dll_ext && sharedname)%>
SOEXT         = <%dll_ext%>
SHTARGETDIR   = <%if(dllout)%><%dllout%><%if(!compares(dllout, .))%><%output_dir_ext%><%endif%><%else%><%libout%><%if(!compares(libout, .))%><%output_dir_ext%><%endif%><%endif%><%slash%><%targetoutdir%>
<%if(version && versupport)%>
SHLIB_BASE    = $(LIBPREFIX)<%sharedname%>$(LIBSUFFIX)$(SOEXT)
<%endif%>
SHLIB         = $(SHTARGETDIR)$(LIBPREFIX)<%sharedname%>$(LIBSUFFIX)$(SOEXT)
<%if(shflags)%>
SHFLAGS       = <%shflags%>
<%endif%>
......
if every thing is ok, by no means it will generate script as above, can anyone help me out?

**Comment by ocielliottc** [comment]
Add the following.  It will instruct MPC to not default the sharedname and thus will only generate for a static library:

sharedname =

**Comment by LukeMouse** [comment]
@ocielliottc It works，thank you very much , you do me a great help. but @jwillemsen Is there a better solution?
