### ISSUE TITLE
[request] adopt vscode-mpc under DOCGroup

### ISSUE THREAD

**Issue by alexchandel** [DOCGroup/MPC#180]
To ease debugging #177, I created a simple VSCode extension to basic support for MPC, which I pushed to [vscode-mpc](https://github.com/alexchandel/vscode-mpc).  This properly should live under the DOCGroup organization before being added to the VSCode extension marketplace.  Could you please fork and adopt this repository?

The extension supports `.mpc` and `.mwc`, and also a little bit of `.mpd` files (code-folding in particular).

**Comment by jwillemsen** [comment]
What about transferring your repo to the @DOCGroup organization and we give you access there?

**Comment by alexchandel** [comment]
Just tried but GH apparently does not allow transfer requests to orgs you don't have repository-creation permissions in, which is really dumb.  You could give me temporary permissions maybe, or I could transfer it to you first.  ![Screen Shot 2023-02-26 at 16 01 34](https://user-images.githubusercontent.com/637714/221440132-6d137aed-6110-48c9-89d3-654e3c8245be.jpg)

**Comment by jwillemsen** [comment]
Feel free to transfer it to me, I will transfer it to DOCGroup

**Comment by alexchandel** [comment]
Transfer request sent.

**Comment by jwillemsen** [comment]
Acceptee, will transfer it to docgroup tomorrow

**Comment by jwillemsen** [comment]
Done

**Comment by alexchandel** [comment]
Thanks.  Does DOCGroup have an Azure DevOps organization ([required to publish VSCode extensions to the marketplace…](https://code.visualstudio.com/api/working-with-extensions/publishing-extension)) yet? Or do you want me to create a personal one and publish it under that?

**Comment by jwillemsen** [comment]
We had something on azure devops for the pipelines, will have a look at that asap

**Comment by alexchandel** [comment]
@jwillemsen Any luck?  Should be simple enough to publish it to the VSCode Extensions Marketplace with an org personal access token.

**Comment by jwillemsen** [comment]
Can't easily find whether we have a DOCGroup organization on azure, probably not
