### ISSUE TITLE
Skipping Files when Generating "make" file

### ISSUE THREAD

**Issue by mdavies2310** [DOCGroup/MPC#185]
Hi,
I am trying to build my own OpenDDS program on Linux and am using MPC to do that. I set everything up and use the command, "$MPC_ROOT/mwc.pl --type make BITData.mwc" It says "generating 'make' output using BITData.mwc" but then skips all of the projects I entered in the mpc file.

"Skipping BITData_Idl (BITData.mpc); it avoids corba_e_micro"
"Skipping BITData_Publisher (BITData.mpc); it avoids corba_e_micro"
"Skipping BITData_Subscriber (BITData.mpc); it avoids corba_e_micro"

Any ideas?

Also side note, the type "gnuace" is not in the help menu and does not work for me.

**Comment by mitza-oci** [comment]
"-type make" is not supported for OpenDDS.  Please open an issue in the OpenDDS repository for OpenDDS questions.
