### ISSUE TITLE
How to config different output directory for cmake according to configuration

### ISSUE THREAD

**Issue by LukeMouse** [DOCGroup/MPC#226]
I use the following script
specific(cmake) {
        Debug::exeout=$(CMAKE_SOURCE_DIR)/bind
        Debug::libout=$(CMAKE_SOURCE_DIR)/bind
        Debug::libpaths+=$(CMAKE_SOURCE_DIR)/bind
	Release::exeout=$(CMAKE_SOURCE_DIR)/bin
        Release::libout=$(CMAKE_SOURCE_DIR)/bin
        Release::libpaths+=$(CMAKE_SOURCE_DIR)/bin
 }
but it doesn't work,
How can I change the env_libout etc. in cmake.mpd.  Long for your help,

**Comment by ocielliottc** [comment]
Hi,

As the template is currently written, this will partially do what you want if you use something like this:

```
  exeout = $(CMAKE_SOURCE_DIR)/bin
  specific(cmake) {
    Debug::env_libout=$(CMAKE_SOURCE_DIR)/bind
    Debug::env_libpaths+=$(CMAKE_SOURCE_DIR)/bind
    Release::env_libout=$(CMAKE_SOURCE_DIR)/bin
    Release::env_libpaths+=$(CMAKE_SOURCE_DIR)/bin
  }
```

The `exeout` keyword cannot be overridden inside a `specific` clause in the `cmake.mpd`'s current state.  This may have been an oversite.  But, I think I assumed that the executable would always go to the `exeout` directory and have a modifier (i.e., 'd').

Setting the others appeared to change the output.  So, I think those may do what you were expecting.

**Comment by LukeMouse** [comment]
> Hi,
> 
> As the template is currently written, this will partially do what you want if you use something like this:
> 
> ```
>   exeout = $(CMAKE_SOURCE_DIR)/bin
>   specific(cmake) {
>     Debug::env_libout=$(CMAKE_SOURCE_DIR)/bind
>     Debug::env_libpaths+=$(CMAKE_SOURCE_DIR)/bind
>     Release::env_libout=$(CMAKE_SOURCE_DIR)/bin
>     Release::env_libpaths+=$(CMAKE_SOURCE_DIR)/bin
>   }
> ```
> 
> The `exeout` keyword cannot be overridden inside a `specific` clause in the `cmake.mpd`'s current state. This may have been an oversite. But, I think I assumed that the executable would always go to the `exeout` directory and have a modifier (i.e., 'd').
> 
> Setting the others appeared to change the output. So, I think those may do what you were expecting.

Thanks for you reply, I managed my thoughts with the following way
1. Change `cmake.mpd` from 
```
<%if(exeout)%>
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY <%env_exeout%>)
<%if(use_lib_modifier)%>
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG <%env_exeout%>)
<%endif%>
<%endif%>
<%if(!exename)%>
<%if(libout)%>
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY <%env_libout%>)
<%if(use_lib_modifier)%>
<%foreach(configurations)%>
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_<%uc(configuration)%> <%env_libout%>)
<%endfor%>
<%endif%>
<%endif%>
<%if(dllout)%>
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY <%env_dllout%>)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY <%env_dllout%>)
<%if(use_lib_modifier)%>
<%foreach(configurations)%>
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_<%uc(configuration)%> <%env_dllout%>)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_<%uc(configuration)%> <%env_dllout%>)
<%endfor%>
<%endif%>
<%else%>
<%if(libout)%>
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY <%env_libout%>)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY <%env_libout%>)
<%if(use_lib_modifier)%>
<%foreach(configurations)%>
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_<%uc(configuration)%> <%env_libout%>)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_<%uc(configuration)%> <%env_libout%>)
<%endfor%>
<%endif%>
<%endif%>
<%endif%>
<%endif%>
```
to 
```
<%if(exename)%>
<%foreach(configurations)%>
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_<%uc(configuration)%> <%exeout%>)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_<%uc(configuration)%> <%libout%>)
<%endfor%>
<%endif%>

<%if(staticname)%>
<%foreach(configurations)%>
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_<%uc(configuration)%> <%libout%>)
<%endfor%>
<%endif%>

<%if(sharedname)%>
<%foreach(configurations)%>
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_<%uc(configuration)%> <%libout%>)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_<%uc(configuration)%> <%dllout%>)
<%endfor%>
<%endif%>
```
2. for exe I use 
```
specific(cmake) {
        Debug::exeout=${CMAKE_SOURCE_DIR}/bind
        Debug::libout=${CMAKE_SOURCE_DIR}/libd
        Debug::libpaths+=${CMAKE_SOURCE_DIR}/libd
	Release::exeout=${CMAKE_SOURCE_DIR}/bin
        Release::libout=${CMAKE_SOURCE_DIR}/lib
        Release::libpaths+=${CMAKE_SOURCE_DIR}/lib
}
```
3. for dynamic library I use 
```
specific(cmake) {
        Debug::dllout=${CMAKE_SOURCE_DIR}/libd		
	Debug::libout=${CMAKE_SOURCE_DIR}/libd
        Debug::libpaths+=${CMAKE_SOURCE_DIR}/libd		
	Release::dllout=${CMAKE_SOURCE_DIR}/lib
	Release::libout=${CMAKE_SOURCE_DIR}/lib
        Release::libpaths+=${CMAKE_SOURCE_DIR}/lib
}
```
3. for static library I use 
```
specific(cmake) {
    Debug::libout=${CMAKE_SOURCE_DIR}/libd
    Debug::libpaths+=${CMAKE_SOURCE_DIR}/libd
    Release::libout=${CMAKE_SOURCE_DIR}/lib
    Release::libpaths+=${CMAKE_SOURCE_DIR}/lib
}
```
This realized my thoughts, MPC is such a perfect tool, I wonder why so many people use CMake

**Comment by mitza-oci** [comment]
Should this change to `cmake.mpd` be a pull request so we can integrate it into the repo?
