### ISSUE TITLE
OpenSSL 1.1 has different library names on Windows 

### ISSUE THREAD

**Issue by jwillemsen** [DOCGroup/MPC#41]
See https://github.com/DOCGroup/ACE_TAO/pull/494, OpenSSL 1.1 and newer have different library names on windows

**Comment by mitza-oci** [comment]
Probably needs to use the same strategy as xerces.mpb to have the user indicate which version it is.

**Comment by jwillemsen** [comment]
Preferable only for windows, for other platforms the library names haven't changes

**Comment by jwillemsen** [comment]
See #42

**Comment by mitza-oci** [comment]
Yes, it worked on my system with vc14.
