### ISSUE TITLE
Selection of ISO C++ Standard with Visual Studio 2017 is not available

### ISSUE THREAD

**Issue by mathersm** [DOCGroup/MPC#44]
It seems as though the project generation for Visual Studio was still based off a vc10-era template. Visual Studio 2017 allows for a compiler switch to target different ISO C++ Standards. There didn't seem to be an available option to set this using a specific statement in MPC files.

I've added a potential solution and submitted a pull request (#43) that adds a new template for vs2017 projects and includes a new tag (LanguageStandard) that can be used to control this new setting.

**Comment by mathersm** [comment]
Pull request #45 provides an alternative approach that simply extends the vc10 template.

**Comment by jwillemsen** [comment]
Merged #45
