### ISSUE TITLE
Name of Makefile for Workspaces

### ISSUE THREAD

**Issue by arturd0** [DOCGroup/MPC#54]
If I have a workspace file named e.g. A.mwc, and use -type make, then mwc.pl generates two files:

Makefile.A, and
Makefile

There is a problem if I have two mwc files in the same directory, since I only can have one single file named Makefile.

Preferably, the names of the generated files should be:
A.project, and A.workspace, or something else similar to this.

**Comment by ocielliottc** [comment]
You can use one of two options to work around this issue:

1) You can add the -notoplevel option to the command line so that the top
level build file is not created.
2) You can generate the first workspace and use the -name_modifier option
to change the top level build file.


$MPC_ROOT/mwc.pl -make A.mwc
$MPC_ROOT/mwc.pl -make -notoplevel B.mwc

or

$MPC_ROOT/mwc.pl -make -name_modifier '*.other' B.mwc

​

**Comment by arturd0** [comment]
But, the top level file is needed at the end. So, rather the second alternative.
Other workarounds would be to put both projects in the same .mwc file, or in different directories.

**Comment by ocielliottc** [comment]
On Tue, Apr 10, 2018 at 9:54 AM, arturd0 <notifications@github.com> wrote:

> But, the top level file is needed at the end. So, rather the second
> alternative.
> Other workarounds would be to put both projects in the same .mwc file, or
> in different directories.
>

That is correct.

**Comment by mitza-oci** [comment]
Would aggregated workspaces help?  I can't tell what the intended usage pattern is based on the info given.

**Comment by ocielliottc** [comment]
On Tue, Apr 10, 2018 at 10:00 AM, Adam Mitz <notifications@github.com>
wrote:

> Would aggregated workspaces help? I can't tell what the intended usage
> pattern is based on the info given.
>

It seems like that could work.   But, I guess it just depends on the
situation.

workspace {
  A.mwc
  B.mwc
}

**Comment by arturd0** [comment]
In general, aggregated workspaces would work. That was in principle what I meant by "... put both projects in the same .mwc file ...".

One situation I can think of, where this can be counterproductive, is when you really want to build A and B separately. In that case -> different directories.

I suppose, we can close the issue.
