### ISSUE TITLE
ERROR: No workspace was defined (on Linux)

### ISSUE THREAD

**Issue by arturd0** [DOCGroup/MPC#55]
Hi,

I'm using very simple .mwc and .mpc files (see attachments).

When you repeat the command a second time:

perl $MPC/mwc.pl -type make testModuleA.mwc -name_modifier  *ABC

Generating 'make' output using testModuleA.mwc
Generation Time: 0s
Generating 'make' output using Makefile.testModuleAABC
Makefile.testModuleAABC: line 1:
ERROR: No workspace was defined
ERROR: Unable to process: Makefile.testModuleAABC
     Total Time: 0s

This only happens on Linux.
I don't understand why "Generating 'make' output using Makefile.testModuleAABC" happens at all!?
No problem without -name_modifier.
Why is MWC trying to parse Makefile.testModuleAABC at all? Why is this only happening on Linux?

[example.zip](https://github.com/DOCGroup/MPC/files/1915339/example.zip)

**Comment by ocielliottc** [comment]
On the Linux command line, you must either escape the * or put it in single
quotes.  The shell is picking up the generated file as input (on the second
time you run this) and is assuming it is a workspace.  MPC does not require
a workspace to actually end in .mwc.

**Comment by arturd0** [comment]
Yes, that was it!
