### ISSUE TITLE
How do I use this to generate ACE makefile in ACE_ROOT?

### ISSUE THREAD

**Issue by jackiilong** [DOCGroup/MPC#64]
I have  cloned ace source , find it has no Makefile

**Comment by jackiilong** [comment]
is there doc for generate

**Comment by jwillemsen** [comment]
See the ACE/ACE-INSTALL.html and TAO/TAO-INSTALL.html within the ACE/TAO source tree, that has the instructions, you have to generate the makefiles with MPC when you directly clone from github. The releases contain generated makefiles for convenience.

**Comment by jwillemsen** [comment]
See download.dre.vanderbilt.edu or the releases on github

**Comment by jackiilong** [comment]
ACE_ROOT/INSTALL.html contains no wpc generation controduction

**Comment by mcorino** [comment]
It's ACE_ROOT/ACE-INSTALL.html and check the paragraph "General MPC information".
