### ISSUE TITLE
-name_modifier creates faulty dependies (parallel independent makefiles for embedded development)

### ISSUE THREAD

**Issue by thomas65g** [DOCGroup/MPC#65]
by inserting -name_modifier colibri_* into the command line the lib order changes and dependencies are not resolvable

```
#! /bin/sh
set -x
ROOT="$(dirname "$(pwd)")"
echo "$ROOT"
perl  ../../tools/mpc/mwc.pl \
  -type make \
  -name_modifier colibri_* \
  -value_template output_dir_ext=/colibri \
  -value_template compilers=arm_colibri_gcc \
  -value_template platforms=colibri_imx6 \
  -include "./baseprojects" \
  -relative PROJ_TOP="$ROOT" \
ws_develop_test.mwc

```
Makefile created without name modifier (compiles and links)

```
ut_mtdiscovery: core gsoap mtdiscovery
	@cd ../3rd/mtdiscovery/unittest && $(MAKE) -f Makefile.ut_mtdiscovery all
```

Makefile created with name_modifier=  colibri_*  creates strange dependencies (cannot resolve libs)
```
ut_mtdiscovery: agg agg2d decfloat freetype png lua mtchart mtdiscovery
	@cd /home/thomas/projects/pdk_linux/tresos-fw/mt-pdk/source/3rd/mtdiscovery/unittest && $(MAKE) -f colibri_Makefile all
```

**Comment by mitza-oci** [comment]
That does look strange.  The first thing to check is how the shell is expanding the `colibri_*` wildcard before running mwc.pl.

**Comment by thomas65g** [comment]
Thanks for the hint.
The shell (bash) expands colibri_* to colibri_Makefile, if a file named colibri_Makefile already exits in current folder.
I put quotation marks and it works.
