### ISSUE TITLE
Option to specify project intermediate objects build directory

### ISSUE THREAD

**Issue by akotulu** [DOCGroup/MPC#73]
Under Project Keywords there is missing a option to specify where *.o files should be placed. This is useful when someone is using a shared network drive for source files.

**Comment by mitza-oci** [comment]
Each generator type handles this differently.  You can use settings within "specific" blocks to customize it, based on capabilities of the different generators.  The variables that can be set in "specific" are documented in docs/templates.

You can also use clone_build_tree.pl to treat the source tree as read-only.
