### ISSUE TITLE
Does MPC support NDK develop

### ISSUE THREAD

**Issue by LukeMouse** [DOCGroup/MPC#86]
Hi there, MPC is a powerful tools for project creation, recently,I changed to android develop with NDK, I wonder if this powerful tool support NDK so development. best regards.

**Comment by mitza-oci** [comment]
Yes, see http://www.dre.vanderbilt.edu/~schmidt/DOC_ROOT/ACE/ACE-INSTALL.html#android for one example.  If you want to use `-type make` instead, it should be work but it may require some changes to `makedll.mpt`.

**Comment by jwillemsen** [comment]
Closing, Android NDK is supported
